server {
    listen 80;
    server_name localhost;

    root /var/www/app;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location = /dashboard {
        return 301 /dashboard/;
    }
    location /dashboard/ {
        alias /var/www/app/pages/dashboard/;
        index dashboard.html;
    }
}
