version: "3.8"

services:

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-init:
    image: mongo:7
    depends_on:
      - mongo
    restart: "no"
    entrypoint: >
      bash -c "
      sleep 5 &&
      mongosh --host mongo:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [{ _id: 0, host: \"mongo:27017\" }]
        })
      '"

  
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ecs,ecr,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock

  
  vectordb:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      
volumes:
  mongo_data:
  redis_data:
  localstack_data: